name: Build and Deploy

on:
  push:
    branches:
      - master

env:
  API_KEY: ${{ secrets.API_KEY }}
  GRAPHQL_ENDPOINT: ${{ secrets.GRAPHQL_ENDPOINT }}

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Start React App
    run: |
      npm start &
      echo "React App Started"

    - name: Check React App
      run: |
      curl localhost:3000
      echo "React App is Running"

    - name: Print environment variables
      run: |
        echo "API_KEY: $API_KEY"
        echo "GRAPHQL_ENDPOINT: $GRAPHQL_ENDPOINT"

    - name: Build
      run: |
        npm ci
        npm run build

    - name: Deploy
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.HOMEPAGE_TOKEN }}
        publish_dir: ./build