name: Build and Deploy

on:
  push:
    branches:
      - master

env:
  REACT_APP_API_KEY: ${{ secrets.REACT_APP_API_KEY }}
  REACT_APP_GRAPHQL_ENDPOINT: ${{ secrets.REACT_APP_GRAPHQL_ENDPOINT }}

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: create env file
      run: |
        touch .env
        echo REACT_APP_API_KEY=${{ secrets.REACT_APP_API_KEY }} >> .env
        echo REACT_APP_GRAPHQL_ENDPOINT=${{ secrets.REACT_APP_GRAPHQL_ENDPOINT }} >> .env

    - name: Install dependencies
      run: |
        npm ci
        npm install @craco/craco

    - name: Print environment variables
      run: |
        echo "API_KEY: $API_KEY"
        echo "GRAPHQL_ENDPOINT: $GRAPHQL_ENDPOINT"

    - name: Build
      run: |
        npm ci
        npm run build

    - name: Deploy
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.HOMEPAGE_TOKEN }}
        publish_dir: ./build